version: "3"
services:
  php:
    container_name: projetoB
    build: ./apache-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
  db:
    container_name: postgres
    build: ./dbpostgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data