version: "3"
services:
  php:
    container_name: projetoC
    build: ./apache-php
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
    links:
      - db
  db:
    container_name: mysql56
    image: mysql:5.6
    ports:
      - "3306:3306"
    volumes:
      - ./mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=exemplo
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user 